# Generated by Django 4.0.4 on 2022-04-24 06:04

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0002_alter_watchlist_platform_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamplatform',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2022, 4, 24, 6, 4, 33, 737220, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
