# Generated by Django 4.0.4 on 2022-04-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0003_streamplatform_slug_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='streamplatform',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
